from typing import List, Dict, Optional
from datetime import datetime
from backend.models import Commodity, MandiMarket, VerifiedBuyer, OrderRequest, PriceForecastPoint, PaymentReceipt

class DataStore:
    def __init__(self):
        self.commodities: Dict[str, Commodity] = {
            "wheat": Commodity(
                id="wheat",
                name="Wheat (गेहूं)",
                hindiName="गेहूं",
                marathiName="गहू",
                icon="🌾",
                category="Cereal",
                currentAvgPrice=2470.0,
                change24h=1.8,
                msp=2275.0,
                moistureStandardPercent=12.0,
                shelfLifeDays=365,
                varieties=["Lokwan", "Sharbati", "Kalyan Sona", "HD-2967"]
            ),
            "soyabean": Commodity(
                id="soyabean",
                name="Soyabean (सोयाबीन)",
                hindiName="सोयाबीन",
                marathiName="सोयाबीन",
                icon="🌱",
                category="Oilseed",
                currentAvgPrice=5120.0,
                change24h=-0.6,
                msp=4600.0,
                moistureStandardPercent=10.0,
                shelfLifeDays=180,
                varieties=["JS-335", "JS-9560", "NRC-37", "Yellow Gold"]
            ),
            "onion": Commodity(
                id="onion",
                name="Onion (प्याज)",
                hindiName="प्याज",
                marathiName="कांदा",
                icon="🧅",
                category="Vegetable",
                currentAvgPrice=2850.0,
                change24h=4.2,
                msp=0.0,
                moistureStandardPercent=14.0,
                shelfLifeDays=90,
                varieties=["Nashik Red", "Garwa (Rabi)", "Pol (Kharif)", "White Onion"]
            ),
            "cotton": Commodity(
                id="cotton",
                name="Cotton (कपास)",
                hindiName="कपास",
                marathiName="कापूस",
                icon="☁️",
                category="Cash Crop",
                currentAvgPrice=7350.0,
                change24h=0.5,
                msp=6620.0,
                moistureStandardPercent=8.5,
                shelfLifeDays=240,
                varieties=["Bt Cotton", "Shankar-6", "DCH-32", "MCU-5"]
            ),
            "chana": Commodity(
                id="chana",
                name="Gram / Chana (चना)",
                hindiName="चना",
                marathiName="हरभरा",
                icon="🧆",
                category="Pulse",
                currentAvgPrice=5850.0,
                change24h=2.1,
                msp=5440.0,
                moistureStandardPercent=9.5,
                shelfLifeDays=300,
                varieties=["Desi Chana", "Kabuli Dollar", "Digvijay", "Vijay"]
            ),
            "rice": Commodity(
                id="rice",
                name="Paddy / Rice (धान)",
                hindiName="धान",
                marathiName="भात/तांदूळ",
                icon="🍚",
                category="Cereal",
                currentAvgPrice=3150.0,
                change24h=1.2,
                msp=2183.0,
                moistureStandardPercent=13.0,
                shelfLifeDays=365,
                varieties=["Basmati 1121", "Pusa Sugandh", "Indrayani", "Wada Kolam"]
            ),
        }

        self.mandis: Dict[str, MandiMarket] = {
            "mandi-nashik": MandiMarket(
                id="mandi-nashik",
                name="Nashik Main APMC",
                district="Nashik",
                state="Maharashtra",
                distanceKm=18,
                modalPrice=2470.0,
                minPrice=2380.0,
                maxPrice=2560.0,
                arrivalTodayQuintals=14200,
                arrivalTrendPercent=8.5,
                verifiedBuyersCount=28,
                storageCapacityAvailableQuintals=45000,
                coldStorageAvailable=True,
                rating=4.8,
                mandiCessPercent=1.05,
                avgHandlingCostPerQuintal=16.0
            ),
            "mandi-pune": MandiMarket(
                id="mandi-pune",
                name="Pune APMC Hub",
                district="Pune",
                state="Maharashtra",
                distanceKm=58,
                modalPrice=2590.0,
                minPrice=2480.0,
                maxPrice=2690.0,
                arrivalTodayQuintals=28400,
                arrivalTrendPercent=12.0,
                verifiedBuyersCount=54,
                storageCapacityAvailableQuintals=120000,
                coldStorageAvailable=True,
                rating=4.9,
                mandiCessPercent=1.2,
                avgHandlingCostPerQuintal=22.0
            ),
            "mandi-lasalgaon": MandiMarket(
                id="mandi-lasalgaon",
                name="Lasalgaon Onion Mandi",
                district="Nashik",
                state="Maharashtra",
                distanceKm=34,
                modalPrice=2520.0,
                minPrice=2410.0,
                maxPrice=2610.0,
                arrivalTodayQuintals=32000,
                arrivalTrendPercent=15.2,
                verifiedBuyersCount=42,
                storageCapacityAvailableQuintals=80000,
                coldStorageAvailable=True,
                rating=4.9,
                mandiCessPercent=1.0,
                avgHandlingCostPerQuintal=15.0
            ),
            "mandi-indore": MandiMarket(
                id="mandi-indore",
                name="Indore Laxmibai Nagar APMC",
                district="Indore",
                state="Madhya Pradesh",
                distanceKm=142,
                modalPrice=2640.0,
                minPrice=2520.0,
                maxPrice=2740.0,
                arrivalTodayQuintals=41000,
                arrivalTrendPercent=-3.4,
                verifiedBuyersCount=68,
                storageCapacityAvailableQuintals=210000,
                coldStorageAvailable=False,
                rating=4.7,
                mandiCessPercent=1.5,
                avgHandlingCostPerQuintal=19.0
            ),
            "mandi-nagpur": MandiMarket(
                id="mandi-nagpur",
                name="Nagpur Kalamna Grain Terminal",
                district="Nagpur",
                state="Maharashtra",
                distanceKm=195,
                modalPrice=2610.0,
                minPrice=2490.0,
                maxPrice=2710.0,
                arrivalTodayQuintals=19500,
                arrivalTrendPercent=4.1,
                verifiedBuyersCount=39,
                storageCapacityAvailableQuintals=95000,
                coldStorageAvailable=True,
                rating=4.6,
                mandiCessPercent=1.1,
                avgHandlingCostPerQuintal=20.0
            ),
        }

        self.buyers: Dict[str, VerifiedBuyer] = {
            "buyer-agrocorp": VerifiedBuyer(
                id="buyer-agrocorp",
                name="Vikram Sethi",
                companyName="AgroCorp India Ltd.",
                type="Processor",
                mandiId="mandi-pune",
                offeredRatePerQuintal=2580.0,
                minVolumeQuintals=50,
                maxVolumeQuintals=500,
                qualitySpecs="Moisture <12%, Shriveled <2%, Foreign Matter <0.5%",
                paymentReliabilityPercent=99,
                rating=4.9,
                reviewsCount=148,
                verifiedBadge=True,
                isoCertified=True,
                deliveryLocation="Pune Central Silo, Hinjewadi Phase 3",
                acceptedCrops=["wheat", "soyabean", "chana"],
                maxMoistureAllowed=12.0,
                avgPaymentReleaseHours=2
            ),
            "buyer-sahyadri": VerifiedBuyer(
                id="buyer-sahyadri",
                name="Sunita Deshmukh",
                companyName="Sahyadri Mega Food Park",
                type="Processor",
                mandiId="mandi-nashik",
                offeredRatePerQuintal=2520.0,
                minVolumeQuintals=25,
                maxVolumeQuintals=300,
                qualitySpecs="Grade A Export Quality, Color sorted, Moisture <12.5%",
                paymentReliabilityPercent=98,
                rating=4.8,
                reviewsCount=96,
                verifiedBadge=True,
                isoCertified=True,
                deliveryLocation="Mohadi Plant, Dindori Road, Nashik",
                acceptedCrops=["wheat", "onion", "soyabean"],
                maxMoistureAllowed=12.5,
                avgPaymentReleaseHours=3
            ),
            "buyer-itc": VerifiedBuyer(
                id="buyer-itc",
                name="Rameshwar Agrawal",
                companyName="ITC e-Choupal Procurement",
                type="FMCG Corporate",
                mandiId="mandi-indore",
                offeredRatePerQuintal=2650.0,
                minVolumeQuintals=100,
                maxVolumeQuintals=2000,
                qualitySpecs="Aashirvaad Gold Standard: Protein >12%, Moisture <11.5%",
                paymentReliabilityPercent=100,
                rating=5.0,
                reviewsCount=312,
                verifiedBadge=True,
                isoCertified=True,
                deliveryLocation="ITC Integrated Hub, Sanwer Road, Indore",
                acceptedCrops=["wheat", "soyabean", "chana"],
                maxMoistureAllowed=11.5,
                avgPaymentReleaseHours=1
            ),
        }

        self.orders: Dict[str, OrderRequest] = {
            "ORD-2026-8812": OrderRequest(
                id="ORD-2026-8812",
                cropId="wheat",
                cropName="Wheat (Lokwan)",
                variety="Lokwan Grade A",
                quantityQuintals=75.0,
                proposedPricePerQuintal=2580.0,
                farmerId="farmer-rajesh",
                farmerName="Rajesh Patel",
                farmerPhone="+91 98220 11442",
                farmerLocation="Niphad Village",
                farmerDistrict="Nashik",
                buyerId="buyer-agrocorp",
                buyerName="Vikram Sethi",
                buyerCompany="AgroCorp India Ltd.",
                targetMarketId="mandi-pune",
                targetMarketName="Pune APMC Hub",
                status="accepted",
                orderOrigin="farmer_proposal",
                moisturePercent=11.8,
                expectedLossPercent=1.2,
                qualityGrade="Grade A (Export)",
                grossAmount=193500.0,
                freightCost=2108.0,
                calculatedNetRealization=189040.0,
                farmerNotes="Moisture tested 11.8%. Stored in dry gunny bags.",
                createdAt="23 Aug 2026, 11:30 AM"
            ),
            "ORD-2026-7490": OrderRequest(
                id="ORD-2026-7490",
                cropId="soyabean",
                cropName="Soyabean (Yellow)",
                variety="JS-335",
                quantityQuintals=120.0,
                proposedPricePerQuintal=5180.0,
                farmerId="farmer-rajesh",
                farmerName="Rajesh Patel",
                farmerPhone="+91 98220 11442",
                farmerLocation="Niphad Village",
                farmerDistrict="Nashik",
                buyerId="buyer-sahyadri",
                buyerName="Sunita Deshmukh",
                buyerCompany="Sahyadri Mega Food Park",
                targetMarketId="mandi-nashik",
                targetMarketName="Nashik Main APMC",
                status="settled",
                orderOrigin="farmer_proposal",
                moisturePercent=9.8,
                expectedLossPercent=0.8,
                qualityGrade="Grade A (Export)",
                grossAmount=621600.0,
                freightCost=1068.0,
                calculatedNetRealization=614316.0,
                createdAt="21 Aug 2026, 09:15 AM",
                paymentReceipt=PaymentReceipt(
                    receiptId="REC-2026-0821-9988",
                    orderId="ORD-2026-7490",
                    utrNumber="UTR-HDFC-20260821-44771122",
                    bankName="HDFC Bank (Agri Escrow)",
                    accountMasked="XX-XXXX-4421",
                    grossAmount=621600.0,
                    freightDeduction=1068.0,
                    handlingAndCess=6216.0,
                    netCreditedAmount=614316.0,
                    payoutTimestamp="21 Aug 2026, 04:30 PM",
                    status="credited",
                    commissionCutPercent=0.0
                )
            )
        }

        self.forecast_data: Dict[str, List[PriceForecastPoint]] = {
            "wheat": [
                PriceForecastPoint(day="Day -6", date="17 Aug", actualPrice=2360, forecastPrice=2360, lowerConfidence=2330, upperConfidence=2390, arrivalVolume=12500),
                PriceForecastPoint(day="Day -5", date="18 Aug", actualPrice=2380, forecastPrice=2375, lowerConfidence=2340, upperConfidence=2410, arrivalVolume=13100),
                PriceForecastPoint(day="Day -4", date="19 Aug", actualPrice=2410, forecastPrice=2400, lowerConfidence=2360, upperConfidence=2440, arrivalVolume=11800),
                PriceForecastPoint(day="Day -3", date="20 Aug", actualPrice=2435, forecastPrice=2425, lowerConfidence=2380, upperConfidence=2470, arrivalVolume=14200),
                PriceForecastPoint(day="Day -2", date="21 Aug", actualPrice=2420, forecastPrice=2430, lowerConfidence=2390, upperConfidence=2480, arrivalVolume=15600),
                PriceForecastPoint(day="Day -1", date="22 Aug", actualPrice=2450, forecastPrice=2445, lowerConfidence=2400, upperConfidence=2490, arrivalVolume=14500),
                PriceForecastPoint(day="Today", date="23 Aug", actualPrice=2470, forecastPrice=2470, lowerConfidence=2420, upperConfidence=2520, arrivalVolume=14000),
                PriceForecastPoint(day="+3 Days", date="26 Aug", forecastPrice=2510, lowerConfidence=2450, upperConfidence=2570, arrivalVolume=12000),
                PriceForecastPoint(day="+7 Days", date="30 Aug", forecastPrice=2565, lowerConfidence=2490, upperConfidence=2640, arrivalVolume=10500),
                PriceForecastPoint(day="+14 Days", date="06 Sep", forecastPrice=2640, lowerConfidence=2550, upperConfidence=2730, arrivalVolume=8900),
                PriceForecastPoint(day="+21 Days", date="13 Sep", forecastPrice=2710, lowerConfidence=2600, upperConfidence=2820, arrivalVolume=7400),
                PriceForecastPoint(day="+30 Days", date="22 Sep", forecastPrice=2780, lowerConfidence=2650, upperConfidence=2910, arrivalVolume=6200),
            ],
            "soyabean": [
                PriceForecastPoint(day="Day -6", date="17 Aug", actualPrice=5080, forecastPrice=5080, lowerConfidence=4990, upperConfidence=5170, arrivalVolume=8500),
                PriceForecastPoint(day="Today", date="23 Aug", actualPrice=5120, forecastPrice=5120, lowerConfidence=5020, upperConfidence=5220, arrivalVolume=9200),
                PriceForecastPoint(day="+7 Days", date="30 Aug", forecastPrice=5240, lowerConfidence=5100, upperConfidence=5380, arrivalVolume=8100),
                PriceForecastPoint(day="+14 Days", date="06 Sep", forecastPrice=5390, lowerConfidence=5220, upperConfidence=5560, arrivalVolume=7200),
                PriceForecastPoint(day="+30 Days", date="22 Sep", forecastPrice=5580, lowerConfidence=5380, upperConfidence=5780, arrivalVolume=6100),
            ],
            "onion": [
                PriceForecastPoint(day="Day -6", date="17 Aug", actualPrice=2620, forecastPrice=2620, lowerConfidence=2500, upperConfidence=2740, arrivalVolume=22000),
                PriceForecastPoint(day="Today", date="23 Aug", actualPrice=2850, forecastPrice=2850, lowerConfidence=2700, upperConfidence=3000, arrivalVolume=25000),
                PriceForecastPoint(day="+7 Days", date="30 Aug", forecastPrice=3050, lowerConfidence=2850, upperConfidence=3250, arrivalVolume=20000),
                PriceForecastPoint(day="+14 Days", date="06 Sep", forecastPrice=3280, lowerConfidence=3020, upperConfidence=3540, arrivalVolume=17000),
                PriceForecastPoint(day="+30 Days", date="22 Sep", forecastPrice=3600, lowerConfidence=3300, upperConfidence=3900, arrivalVolume=14000),
            ]
        }

db = DataStore()
