import React, { useEffect, useState } from 'react';
import { KisanSetuApi } from '../../services/api';
import { Check, PlusCircle, X } from 'lucide-react';

const token = () => localStorage.getItem('kisansetu_access_token') || '';
const emptyDemand = { cropName: 'Wheat', cropCategory: 'Grain', quantityQuintals: 100, offeredPricePerQuintal: 2700, qualityGrade: 'Grade A', deliveryLocation: '', deadline: '', notes: '' };

export const BuyerDemandWorkflow: React.FC = () => {
  const [demands, setDemands] = useState<any[]>([]); const [offers, setOffers] = useState<any[]>([]);
  const [selected, setSelected] = useState<string>(''); const [form, setForm] = useState(emptyDemand); const [error, setError] = useState('');
  const load = async () => { try { setDemands(await KisanSetuApi.getDemands(token())); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load demands'); } };
  useEffect(() => { load(); }, []);
  const showOffers = async (id: string) => { setSelected(id); setOffers(await KisanSetuApi.getDemandOffers(token(), id)); };
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { await KisanSetuApi.createDemand(token(), { ...form, deadline: new Date(form.deadline).toISOString() }); setForm(emptyDemand); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Could not create demand'); } };
  const respond = async (id: string, action: 'accept' | 'reject' | 'counter', offer: any) => { try { const payload = action === 'counter' ? { offeredQuantityQuintals: offer.offeredQuantityQuintals, offeredPricePerQuintal: Number(prompt('Counter price per quintal', String(offer.offeredPricePerQuintal)) || 0), qualityGrade: offer.qualityGrade, message: 'Buyer counter offer' } : undefined; if (payload && payload.offeredPricePerQuintal <= 0) return; await KisanSetuApi.respondToOffer(token(), id, action, payload); await showOffers(selected); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Action failed'); } };
  return <div className="space-y-5"><div className="clean-card p-5 space-y-3"><div className="flex items-center gap-2"><PlusCircle className="w-5 h-5 text-[#15803D]" /><h2 className="font-bold text-[#1F2937]">Create authenticated crop demand</h2></div><form onSubmit={create} className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">{Object.entries(form).map(([key, value]) => <input key={key} required={key !== 'notes'} type={key === 'deadline' ? 'datetime-local' : ['quantityQuintals','offeredPricePerQuintal'].includes(key) ? 'number' : 'text'} value={value as string | number} onChange={e => setForm({ ...form, [key]: ['quantityQuintals','offeredPricePerQuintal'].includes(key) ? Number(e.target.value) : e.target.value })} placeholder={key.replace(/([A-Z])/g, ' $1')} className="border border-[#D1D5DB] rounded-lg px-3 py-2" />)}<button className="bg-[#2E7D32] text-white rounded-lg px-3 py-2 font-bold">Publish demand</button></form></div>{error && <p className="text-xs text-red-600">{error}</p>}<div className="grid lg:grid-cols-2 gap-4"><div className="space-y-3">{demands.map(d => <button key={d.id} onClick={() => showOffers(d.id)} className="text-left w-full clean-card p-4 text-xs"><b>{d.cropName}</b> · {d.quantityQuintals} qtl @ ₹{d.offeredPricePerQuintal}/q <span className="float-right text-[#15803D]">{d.status}</span><p className="text-[#6B7280] mt-1">{d.deliveryLocation} · {d.deadline.slice(0, 16).replace('T', ' ')}</p></button>)}</div><div className="space-y-3"><h3 className="font-bold text-sm">Farmer offers</h3>{selected && offers.length === 0 && <p className="text-xs text-[#6B7280]">No offers yet.</p>}{offers.map(o => <div key={o.id} className="clean-card p-4 text-xs"><b>{o.farmerName}</b> · {o.offeredQuantityQuintals} qtl @ ₹{o.offeredPricePerQuintal}/q <span className="float-right">{o.status}</span><p className="my-2 text-[#6B7280]">{o.message}</p>{o.status === 'PENDING' && <div className="flex gap-2"><button onClick={() => respond(o.id,'accept',o)} className="text-[#15803D]"><Check className="inline w-3" /> Accept</button><button onClick={() => respond(o.id,'counter',o)}>Counter</button><button onClick={() => respond(o.id,'reject',o)} className="text-red-600"><X className="inline w-3" /> Reject</button></div>}</div>)}</div></div></div>;
};
