import React, { useEffect, useState } from 'react';
import { KisanSetuApi } from '../../services/api';
const token = () => localStorage.getItem('kisansetu_access_token') || '';

export const DemandMarketplace: React.FC = () => {
  const [demands, setDemands] = useState<any[]>([]); const [deals, setDeals] = useState<any[]>([]); const [offers, setOffers] = useState<any[]>([]); const [error, setError] = useState('');
  const load = async () => { try { const [d, x, o] = await Promise.all([KisanSetuApi.getDemands(token()), KisanSetuApi.getDeals(token()), KisanSetuApi.getMyOffers(token())]); setDemands(d); setDeals(x); setOffers(o); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load marketplace'); } };
  useEffect(() => { load(); }, []);
  const offer = async (d: any) => { const quantity = Number(prompt('Offer quantity (quintals)', String(d.quantityQuintals)) || 0); const price = Number(prompt('Offer price per quintal', String(d.offeredPricePerQuintal)) || 0); if (!quantity || !price) return; try { await KisanSetuApi.createDemandOffer(token(), d.id, { offeredQuantityQuintals: quantity, offeredPricePerQuintal: price, qualityGrade: d.qualityGrade, message: 'Farmer offer' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Offer failed'); } };
  const respond = async (o: any, action: 'accept' | 'reject' | 'counter') => { try { const payload = action === 'counter' ? { offeredQuantityQuintals: o.offeredQuantityQuintals, offeredPricePerQuintal: Number(prompt('Your counter price per quintal', String(o.offeredPricePerQuintal)) || 0), qualityGrade: o.qualityGrade, message: 'Farmer counter offer' } : undefined; if (payload && payload.offeredPricePerQuintal <= 0) return; await KisanSetuApi.respondToOffer(token(), o.id, action, payload); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Response failed'); } };
  return <div className="space-y-5"><div><h2 className="text-lg font-bold text-[#1F2937]">Live buyer demands</h2><p className="text-xs text-[#6B7280]">Only demands from authenticated buyer accounts are listed.</p></div>{error && <p className="text-xs text-red-600">{error}</p>}<div className="grid md:grid-cols-2 gap-3">{demands.map(d => <div key={d.id} className="clean-card p-4 text-xs"><div className="flex justify-between"><b>{d.cropName} · {d.cropCategory}</b><span className="text-[#15803D]">Verified buyer</span></div><p className="mt-2">{d.buyerFirmName}: {d.quantityQuintals} qtl @ <b>₹{d.offeredPricePerQuintal}/q</b></p><p className="text-[#6B7280] mt-1">{d.qualityGrade} · Delivery: {d.deliveryLocation}</p><button onClick={() => offer(d)} className="mt-3 px-3 py-1.5 rounded-lg bg-[#2E7D32] text-white font-bold">Make offer</button></div>)}</div><div className="grid md:grid-cols-2 gap-3"><div className="clean-card p-4"><h3 className="font-bold text-sm text-[#1F2937]">My offers</h3>{offers.map(o => <div key={o.id} className="mt-3 text-xs border-t pt-3"><b>{o.offeredQuantityQuintals} qtl @ ₹{o.offeredPricePerQuintal}/q</b> <span className="float-right">{o.status}</span>{o.status === 'COUNTERED' && <div className="mt-2 flex gap-2"><button onClick={() => respond(o, 'accept')} className="text-[#15803D]">Accept</button><button onClick={() => respond(o, 'counter')}>Counter</button><button onClick={() => respond(o, 'reject')} className="text-red-600">Reject</button></div>}</div>)}{offers.length === 0 && <p className="text-xs text-[#6B7280] mt-2">No offers submitted yet.</p>}</div><div className="clean-card p-4"><h3 className="font-bold text-sm text-[#1F2937]">My agreed deals</h3>{deals.map(d => <div key={d.id} className="mt-3 text-xs border-t pt-3"><b>{d.dealCode}</b> · {d.cropName} · ₹{d.grossAmount.toLocaleString('en-IN')}<br />Secure logistics password: <code className="font-bold">{d.dealPassword}</code></div>)}{deals.length === 0 && <p className="text-xs text-[#6B7280] mt-2">No completed deals yet.</p>}</div></div></div>;
};
