import React, { useEffect, useState } from 'react';
import { KisanSetuApi } from '../../services/api';

type Payment = { tradeDealId: string; dealCode: string; cropName: string; amount: number; status: string; releaseReference?: string };
type Shipment = { tradeDealId: string; dealCode: string; providerName?: string; freightAmount?: number; freightPaymentStatus?: string; freightPaymentReference?: string };
export const BuyerPayments: React.FC = () => {
  const token = localStorage.getItem('kisansetu_access_token') || ''; const [payments, setPayments] = useState<Payment[]>([]); const [shipments, setShipments] = useState<Shipment[]>([]); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const load = async () => { try { const [paymentRows, shipmentRows] = await Promise.all([KisanSetuApi.getPayments(token), KisanSetuApi.getBuyerShipments(token)]); setPayments(paymentRows); setShipments(shipmentRows); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load payment records.'); } };
  useEffect(() => { load(); }, []);
  const pay = async (dealId: string, freight = false) => { if (!window.confirm(`Confirm this simulated ${freight ? 'logistics' : 'trade'} payment?`)) return; try { setBusy(dealId); await (freight ? KisanSetuApi.payFreight(token, dealId) : KisanSetuApi.payDealNow(token, dealId)); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Payment could not be completed.'); } finally { setBusy(''); } };
  return <section className="space-y-4"><div><h2 className="text-lg font-bold">Payments</h2><p className="text-xs text-[#6B7280]">Simulated payments are recorded by the backend.</p></div>{error && <p className="text-xs text-[#B91C1C]">{error}</p>}<div className="grid gap-3 md:grid-cols-2">{payments.map((payment) => <div key={payment.tradeDealId} className="clean-card p-4 text-sm space-y-2"><div className="flex justify-between gap-2"><b>{payment.dealCode}</b><span className={`text-xs font-bold ${payment.status === 'RELEASED' ? 'text-[#15803D]' : 'text-[#B45309]'}`}>{payment.status === 'RELEASED' ? 'PAID' : payment.status}</span></div><p className="text-xs text-[#6B7280]">{payment.cropName}</p><p className="font-bold">₹{payment.amount.toLocaleString('en-IN')}</p>{payment.status === 'RELEASED' ? <p className="text-xs text-[#6B7280]">Reference: {payment.releaseReference}</p> : <button disabled={busy === payment.tradeDealId} onClick={() => pay(payment.tradeDealId)} className="rounded-lg bg-[#15803D] px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{busy === payment.tradeDealId ? 'Processing…' : 'Pay Now'}</button>}</div>)}</div><div className="space-y-2"><h3 className="font-bold text-sm">Logistics payments</h3>{shipments.length === 0 ? <p className="text-sm text-[#6B7280]">No assigned logistics payments yet.</p> : shipments.map((shipment) => <div key={shipment.tradeDealId} className="clean-card p-4 text-sm flex flex-wrap items-center justify-between gap-3"><div><b>{shipment.dealCode}</b><p className="text-xs text-[#6B7280]">{shipment.providerName || 'Logistics provider'} · ₹{shipment.freightAmount?.toLocaleString('en-IN') || 0}</p></div>{shipment.freightPaymentStatus === 'PAID' ? <span className="text-xs font-bold text-[#15803D]">PAID · {shipment.freightPaymentReference}</span> : <button disabled={busy === shipment.tradeDealId || !shipment.freightAmount} onClick={() => pay(shipment.tradeDealId, true)} className="rounded-lg bg-[#1D4ED8] px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Pay Logistics</button>}</div>)}</div></section>;
};
